/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        m3: {
          primary: '#d97706',
          'on-primary': '#ffffff',
          'primary-container': '#f59e0b',
          'on-primary-container': '#451a03',
          secondary: '#6b7280',
          'on-secondary': '#ffffff',
          'secondary-container': '#e5e7eb',
          'on-secondary-container': '#1f2937',
          tertiary: '#3b82f6',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#93c5fd',
          'on-tertiary-container': '#1e3a5f',
          error: '#ef4444',
          'on-error': '#ffffff',
          'error-container': '#fca5a5',
          'on-error-container': '#7f1d1d',
          surface: '#0f0f17',
          'on-surface': '#e5e7eb',
          'on-surface-variant': '#9ca3af',
          'surface-container-lowest': '#0a0a0f',
          'surface-container-low': '#111118',
          'surface-container': '#16161f',
          'surface-container-high': '#1c1c27',
          'surface-container-highest': '#23232f',
          'inverse-surface': '#e5e7eb',
          'inverse-on-surface': '#1f2937',
          outline: '#374151',
          'outline-variant': '#1f2937',
          success: '#22c55e',
          'on-success': '#ffffff',
          'success-container': '#bbf7d0',
        },
        mine: {
          bg: '#0a0a0f',
          card: '#16161f',
          border: '#1f2937',
          accent: '#f59e0b',
          orange: '#f59e0b',
          gold: '#d97706',
          'dark-orange': '#92400e',
          warmWhite: '#fef3c7',
          text: '#e5e7eb',
          success: '#22c55e',
          fail: '#ef4444',
          muted: '#9ca3af',
        },
      },
      fontFamily: {
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        'mono-title': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px' }],
        'display-md': ['45px', { lineHeight: '52px' }],
        'display-sm': ['36px', { lineHeight: '44px' }],
        'headline-lg': ['32px', { lineHeight: '40px' }],
        'headline-md': ['28px', { lineHeight: '36px' }],
        'headline-sm': ['24px', { lineHeight: '32px' }],
        'title-lg': ['22px', { lineHeight: '28px' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15px' }],
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.4px' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
      },
      borderRadius: {
        'm3-xs': '4px',
        'm3-sm': '8px',
        'm3-md': '12px',
        'm3-lg': '16px',
        'm3-xl': '28px',
        'm3-full': '9999px',
      },
      spacing: {
        'm3-1': '4px',
        'm3-2': '8px',
        'm3-3': '12px',
        'm3-4': '16px',
        'm3-5': '20px',
        'm3-6': '24px',
        'm3-8': '32px',
        'm3-10': '40px',
        'm3-12': '48px',
      },
      animation: {
        pulse_slow: "pulse-slow 3s ease-in-out infinite",
        glow: "glow 2s ease-in-out infinite alternate",
        numberPop: "number-pop 0.4s ease-out",
        fadeIn: "fade-in 0.3s ease-out",
        pulseOrange: "pulse-orange 2s ease-in-out infinite",
        'm3-ripple': "m3-ripple 0.3s ease-out",
        miningLaunch: "mining-launch 0.5s ease-out",
        successGlow: "success-glow 0.8s ease-out",
        failShake: "fail-shake 0.4s ease-out",
        metricPop: "metric-pop 0.35s ease-out",
        slideIn: "slide-in-right 0.2s ease-out",
        floatUp: "float-up 1s ease-out forwards",
        pulseBorder: "pulse-border 2s ease-in-out infinite",
        signalBreathe: "signal-breathe 2s ease-in-out infinite",
      },
      keyframes: {
        "pulse-slow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
        glow: {
          "0%": { boxShadow: "0 0 5px rgba(245, 158, 11, 0.2)" },
          "100%": { boxShadow: "0 0 20px rgba(245, 158, 11, 0.4)" },
        },
        "number-pop": {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.15)" },
          "100%": { transform: "scale(1)" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-orange": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(245, 158, 11, 0.3)" },
          "50%": { boxShadow: "0 0 0 6px rgba(245, 158, 11, 0)" },
        },
        "m3-ripple": {
          "0%": { transform: "scale(0)", opacity: "0.2" },
          "100%": { transform: "scale(2.5)", opacity: "0" },
        },
        "mining-launch": {
          "0%": { transform: "scale(1)" },
          "30%": { transform: "scale(1.08)" },
          "60%": { transform: "scale(0.96)" },
          "100%": { transform: "scale(1)" },
        },
        "success-glow": {
          "0%": { boxShadow: "0 0 0 0 rgba(34, 197, 94, 0.4)" },
          "50%": { boxShadow: "0 0 16px 4px rgba(34, 197, 94, 0.2)" },
          "100%": { boxShadow: "0 0 0 0 rgba(34, 197, 94, 0)" },
        },
        "fail-shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "20%": { transform: "translateX(-3px)" },
          "40%": { transform: "translateX(3px)" },
          "60%": { transform: "translateX(-2px)" },
          "80%": { transform: "translateX(2px)" },
        },
        "metric-pop": {
          "0%": { transform: "scale(1)" },
          "40%": { transform: "scale(1.12)" },
          "100%": { transform: "scale(1)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(-8px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "float-up": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(-24px)" },
        },
        "pulse-border": {
          "0%, 100%": { borderColor: "rgba(217, 119, 6, 0.3)" },
          "50%": { borderColor: "rgba(217, 119, 6, 0.7)" },
        },
        "signal-breathe": {
          "0%, 100%": { opacity: "1", boxShadow: "0 0 6px rgba(245, 158, 11, 0.4)" },
          "50%": { opacity: "0.6", boxShadow: "0 0 12px rgba(245, 158, 11, 0.6)" },
        },
      },
    },
  },
  plugins: [],
};
